# This is the configuration file for deploying the BSE Bot on Render.
# 1. Commit this file to your GitHub repository.
# 2. Go to the Render dashboard and create a new "Blueprint Instance".
# 3. Connect the repository containing this file.
# 4. Fill in the required Environment Variables in the Render UI.

services:
  - type: web
    name: bse-monitor
    plan: free
    runtime: python
    env: python
    pythonVersion: '3.11'
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: CRON_SECRET_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-1.5-flash
